# -*- coding: utf-8 -*-
"""lvadsusr146_Chekuri_Pooja_Sree_BPA_Lab4_FA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jOzeSIgg0gtR-lAcMWDJ-XdKg1JyID_M

Lab 4 Anomaly Detection
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.ensemble import IsolationForest
from sklearn.metrics import confusion_matrix, classification_report

data=pd.read_csv('/content/anomaly_train.csv')
df=pd.DataFrame(data)

df.head()

df.info()

df.describe()

df.isnull().sum()

df.duplicated().sum()

df.shape

"""Univariate Analysis"""

for i in df.select_dtypes(include=['int64','float64']).columns:
  plt.figure(figsize=(10,5))
  sns.histplot(df[i])
  plt.title(f'Hisogram of {i}')
  plt.xlabel(i)
  plt.show()

for i in df.select_dtypes(include='object').columns:
  plt.figure(figsize=(10,5))
  df[i].value_counts().nlargest(5).plot(kind='bar')
  plt.title(f'Bar chart of {i}')
  plt.xlabel(i)
  plt.ylabel('Count')
  plt.show()

"""Bivariate Analysis"""

numerical=df.select_dtypes(include=['int64','float64']).columns
correlation_matrix=df[numerical].corr()
print(correlation_matrix)

sns.heatmap(correlation_matrix,annot=True,fmt='.2f',cmap='coolwarm')

"""Encoding"""

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for i in df.select_dtypes(include='object').columns:
  df[i]=le.fit_transform(df[i])

iso=IsolationForest(n_estimators=100,contamination=0.1,random_state=42)
scaler=MinMaxScaler()
df_scaled=pd.DataFrame(scaler.fit_transform(df),columns=df.columns)
iso.fit(df_scaled)
y_predict=iso.predict(df_scaled)
df_scaled['anom_score']=iso.decision_function(df_scaled)
df_scaled['anomaly']=np.where(y_predict==1,'no','yes')

df_scaled.head()

sns.scatterplot(x='Amount',y='anom_score',hue='anomaly',data=df_scaled)
plt.show()