# -*- coding: utf-8 -*-
"""lvadsusr146_Chekuri_Pooja_Sree_BPA_Lab2_FA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fPHm7Vw0MECCiBJjmWvfERe2m3WbcFnf

Lab 2 Classification
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

data=pd.read_csv('/content/penguins_classification.csv')
df=pd.DataFrame(data)

df.head()

df.info()

df.describe()

df.isnull().sum()

df['bill_depth_mm']=df['bill_depth_mm'].fillna(df['bill_depth_mm'].mean())

df.shape

df.duplicated().sum()

"""Univariate Analysis"""

for i in df.select_dtypes(include=['int64','float64']).columns:
  plt.figure(figsize=(10,5))
  sns.histplot(df[i])
  plt.title(f'Hisogram of {i}')
  plt.xlabel(i)
  plt.show()

for i in df.select_dtypes(include='object').columns:
  plt.figure(figsize=(10,5))
  df[i].value_counts().nlargest(5).plot(kind='bar')
  plt.title(f'Bar chart of {i}')
  plt.xlabel(i)
  plt.ylabel('Count')
  plt.show()

"""Handling Outliers"""

for i in df.select_dtypes(include=['int64','float64']).columns:
  plt.figure(figsize=(10,5))
  sns.boxplot(df[i])
  plt.title(f'boxplot of {i}')
  plt.xlabel(i)
  plt.show()

for i in df.select_dtypes(include=['int64','float64']).columns:
  q1=df[i].quantile(0.25)
  q3=df[i].quantile(0.75)
  iqr=q1-q3
  l=q1-1.5*iqr
  u=q3+1.5*iqr
  df[i]=df[i].clip(lower=l,upper=u)
  sns.boxplot(df[i])
  plt.show()

df.shape

"""Bivariate Analysis"""

numerical=df.select_dtypes(include=['int64','float64']).columns
correlation_matrix=df[numerical].corr()
print(correlation_matrix)

sns.heatmap(correlation_matrix,annot=True,fmt='.2f',cmap='coolwarm')

df.columns

x=df.drop('species',axis=1)
y=df['species']
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for i in x.select_dtypes(include='object').columns:
  x[i]=le.fit_transform(x[i])

from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
log=LogisticRegression()
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
scaler=MinMaxScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)
log.fit(x_train_scaled,y_train)
y_predict= log.predict(x_test_scaled)

from sklearn.metrics import classification_report,confusion_matrix
print('Using Logistic Regression')
conf=confusion_matrix(y_test,y_predict)
print("confusion matrix:")
print(conf)
classi=classification_report(y_test,y_predict)
print("classification report:")
print(classi)

rf=RandomForestClassifier(n_estimators=100,random_state=42)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
scaler=MinMaxScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)
rf.fit(x_train_scaled,y_train)
y_predict= rf.predict(x_test_scaled)

from sklearn.metrics import classification_report,confusion_matrix
print('Using Random Forest Classifier:')
conf=confusion_matrix(y_test,y_predict)
print("confusion matrix:")
print(conf)
classi=classification_report(y_test,y_predict)
print("classification report:")
print(classi)