# -*- coding: utf-8 -*-
"""lvadsusr146_chekuri_pooja_sree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tnQB1caiberCx7Z-jgfU0nIgw0YK89Zz

1.
"""

print("enter the length in meters:")
length=int(input())
print("enter the width in meters :")
width=int(input())
area=length*width
if area<1000:
  print("Area is:",area,"m^2","small property")
elif area<2500:
  print("Area is:",area,"m^2","medium property")
else:
  print("Area is:",area,"m^2","large property")

"""2."""

class body_mass():
  def __init__(self,wei,hei):
    self.wei=wei
    self.hei=hei
  def bodymassindex(self):
    return (self.wei/(self.hei^2))
print("enter weight in kgs:")
weight=float(input())
print("enter height in meters:")
height=int(input())
bmi=body_mass(weight,height)
print("Body mass index is:",bmi.bodymassindex())

"""3."""

class students():
  def __init__(self,id,name,maths=0,physics=0,chemistry=0):
    self.id=id
    self.name=name
    self.maths=maths
    self.physics=physics
    self.chemistry=chemistry
  def show(self):
    print('name',self.name)
    print('maths',self.maths)

"""4."""

print("Enter age:")
age=int(input())
def category(age):
  if age<10:
    print("childern category")
    print("shows:abc,bnh,khj")
  elif age<18:
    print("teen category")
    print("shows:huio,hdje,friends")
  elif age<45:
    print("adult category")
    print("shows:aghd,dahjb,vdh")
  else:
    print("senior category")
    print("shows:ahdjb,dhd,hdb")

x=category(age)

"""5."""

print("no of subscribers:")
n=int(input())
s=[]
for i in range(n):
  print("enter subscriber id:")
  x=int(input())
  s.append(x)
print("subscribers all:",s)
def even_subscribers(l):
  even=[]
  for i in l:
    if i%2==0:
      even.append(i)
  return even
print("even id subscribers:",even_subscribers(s))

"""6."""

p=str(input())
i=0
while i==0:
  if p=='bertyw':
    i=i+1
    print("file opened")
  else:
    continue

"""7."""

print("no of customers:")
n=int(input())
f=[]
sum=0
for i in range(n):
  print("name:")
  a=str(input())
  print("score:")
  b=float(input())
  f.append(b)
for j in f:
  sum=sum+j
avg=sum/n
print("average score",avg)

"""8.

"""

comment=str(input())
count=0
for i in comment:
  if i in ("a","e","i","o","u"):
    count=count+1
print("count of vowels",count)

"""9."""



"""10."""

def loanrepayment(amount,repaid):
  r=0
  try:
    r=amount-repaid
  except:
    print("error in loan repayment")
  return r
def savings_interest(amount,inter):
  r=0
  try:
    r=amount+(amount*inter)
  except:
    print("eroor in savings_interest")
  return r
amount=float(input())
repaid=float(input())
inter=float(input())
loanrepayment(amount,repaid)
savings_interest(amount,inter)

"""11"""



"""12"""

num1=int(input())
num2=int(input())
def addition(num1,num2):
  print(num1+num2)
def division(num1,num2):
  try:
    print(num1/num2)
  except ZeroDivisionError:
    print("division error")
addition(num1,num2)
division(num1,num2)

"""13."""

