# -*- coding: utf-8 -*-
"""lvadsusr146_chekuri_pooja_sree_IA_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19CqmYd1jx3UAqoMwzJbX6k_hOGYSq8kM

1.
"""

import numpy as np

arr=np.array([1,4,6,2,8,2,8,9])
arr2=np.array([2,5,6,7,8,3,7,9])
minimum=np.min(arr)
maximum=np.max(arr)
arr_sum=np.sum(arr)
arr_mean=np.mean(arr)
arr_std=np.std(arr)
print("minimum:",minimum)
print("maximum:",maximum)
print("sum:",arr_sum)
print('mean:',arr_mean)
print("standard deviation:",arr_std)

"""2."""

import numpy as np
health_data = np.array([[160, 70, 30],   # height, weight, age for individual 1
                        [165, 65, 35],   # height, weight, age for individual 2
                        [170, 75, 40]])  # height, weight, age for individual 3

"""3."""



"""4."""

import numpy as np

temp=np.linspace(15,25,24)
print(temp)

"""5."""

import numpy as np
daily_closing_prices = np.array([100, 102, 98, 105, 107, 110, 108, 112, 115, 118, 120])
window_size = 5
l=daily_closing_prices.size
mv_avg=[]
for i in range(0,l-window_size+1):
  avg=np.mean(daily_closing_prices[i:i+window_size])
  mv_avg.append(avg)
  i=i+1
print(mv_avg)

"""6."""



"""7."""

import numpy as np
properties_matrix = np.array([[1, 2, 3],
                              [4, 5, 6],
                              [7, 8, 9]])
determinant=np.det(properties_matrix)

"""8."""

import numpy as np

mat=np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(mat.shape)
condition= mat>5 #boolean indexing
print(condition)
r=mat[condition]
print(r)

"""9."""

import pandas as pd
import numpy as np
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace'],
        'Age': [25, 30, 35, 40, 45, 50, 55],
        'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Miami', 'Boston'],
        'Department': ['HR', 'IT', 'Finance', 'Marketing', 'Sales', 'IT', 'HR']}
df=pd.DataFrame(data)
req=pd.DataFrame(df[(df['Age']<45) & (df['Department']!='HR')].head(),columns=['Name','City'])
print(req)

"""10."""

import pandas as pd
import numpy as np
data = {'Department': ['Electronics', 'Electronics', 'Clothing', 'Clothing', 'Home Goods'],
        'Salesperson': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
        'Sales': [70000, 50000, 30000, 40000, 60000]}
df=pd.DataFrame(data)
avg=df.groupby(['Department','Salesperson']).aggregate({'Sales':'mean'})
print(avg)
r=df.groupby(['Department']).aggregate({'Sales':'mean'})
r['rank']=r.aggregate({'Sales':'rank'})
print(r)

"""11."""

import pandas as pd
import numpy as np
data = {
    'Product': ['Apples', 'Bananas', 'Cherries', 'Dates', 'Elderberries', 'Flour', 'Grapes'],
    'Category': ['Fruit', 'Fruit', 'Fruit', 'Fruit', 'Fruit', 'Bakery', 'Fruit'],
    'Price': [1.20, 0.50, 3.00, 2.50, 4.00, 1.50, 2.00],
    'Promotion': [True, False, True, True, False, True, False]
}
df=pd.DataFrame(data)
req=pd.DataFrame(df[(df['Category']=='Fruit') & (df['Price']>(df.groupby('Category').aggregate({'Price':"mean"}))) & (df['Promotion']==False)].head(),
                 columns=['Product'])

"""12."""

import pandas as pd
employee_data = {
    'Employee': ['Alice', 'Bob', 'Charlie', 'David'],
    'Department': ['HR', 'IT', 'Finance', 'IT'],
    'Manager': ['John', 'Rachel', 'Emily', 'Rachel']
}

# Dataset of employee project assignments
project_data = {
    'Employee': ['Alice', 'Charlie', 'Eve'],
    'Project': ['P1', 'P3', 'P2']
}
r=pd.DataFrame(project_data)
df=pd.DataFrame(employee_data)

"""13."""

import pandas as pd
df=pd.read_csv('/content/Q13_sports_team_stats.csv')
print(df)
req=df.groupby('TeamID').agg('sum')
print(req)

"""14."""

import pandas as pd
df=pd.read_csv("/content/Q14_customer_purchases.csv")
print(df)
req=df.groupby('LoyaltyProgramSignUp').agg('count')
print(req)

"""15."""

import pandas as pd
df=pd.read_csv('/content/Q15_student_grades.csv')
print(df)
req=df.req=df.groupby('Subject').agg({'Grade':'mean'})
print(req)