# -*- coding: utf-8 -*-
"""lvadsusr146_chekuri_pooja_sree_ia2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WTiBZh7vwkPfvx2K20psIOMAnIY9XkhB

Load Data Clusttering
"""

import pandas as pd
import seaborn as sns
data=pd.read_csv('/content/Mall_Customers.csv')
df=pd.DataFrame(data)

df.info()

df.describe()

df.isnull().sum()

df.duplicated().sum()

import matplotlib.pyplot as plt
import seaborn as sns

for i in df.select_dtypes(include=['int64','float64']):
  plt.figure(figsize=(10,5))
  sns.boxplot(df[i])
  plt.title(f'Boxplot of {i}')
  plt.xlabel(i)
  plt.show()

for i in df.select_dtypes(include=['int64','float64']):
  q1=df[i].quantile(0.25)
  q3=df[i].quantile(0.75)
  iqr=q3-q1
  l=q1-1.5*iqr
  u=q3+1.5*iqr
  df[i]=df[i].clip(lower=l,upper=u)
  sns.boxplot(df[i])
  plt.show()

from sklearn.preprocessing import LabelEncoder
lbl=LabelEncoder()
for i in df.select_dtypes(include='object').columns:
  df[i]=lbl.fit_transform(df[i])

df.head()

from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler
km=KMeans(n_clusters=3)
km.fit_predict(df)

