# -*- coding: utf-8 -*-
"""lvadsusr146_Chekuri_Pooja_Sree_Final_Assessment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QP_hHcbSIkYQEmRYsO_RZQuWP1LUv9XW

1.a,b
"""

import pandas as pd
data=pd.read_csv('/content/Final Dataset - IPL.csv')
df=pd.DataFrame(data)
df.head() # gives five rows of df
df.describe() # describes the data
df.info() # gives the info of data (column name,non null count,dtype)
columns=df.columns
print(columns.size) # no of columns
df.count() # no of rows
categorical_data=df.select_dtypes(include=object) # gives all the categorical data
numerical_data=df.select_dtypes(exclude=object) # gives all the numerical data
print(numerical_data)
print(categorical_data)
df.isnull().sum() # checks for missing values
df.isna().sum()

"""2.a there are no missing values in the given data
if there are any missing values in the data then we can use fillna('value',inplace=True) to insert the values in the missing cell or we can drop the column or row by using dropna() for rows and dropna(axis=1) for columns
"""

df.isnull().sum()
df.isna().sum()

"""2.b by using the function drop_duplicates we can delete the duplicate values from the dataframe since there are no duplicates in the data we got the same data after removing the duplicates"""

data=pd.read_csv('/content/Final Dataset - IPL.csv')
df=pd.DataFrame(data)
a=df.drop_duplicates()
a.info()

"""3.mean,median,mode,range,variance and standard deviation"""

import pandas as pd
data=pd.read_csv('/content/Final Dataset - IPL.csv')
df=pd.DataFrame(data)
categorical_data=df.select_dtypes(include=object) # gives all the categorical data
numerical_data=df.select_dtypes(exclude=object) # gives all the numerical data
mean_df=numerical_data.agg('mean')
median_df=numerical_data.agg('median')
col=numerical_data.columns
mode_df=numerical_data.agg('mode')
print("Mean:")
print(mean_df)
print('Median:')
print(median_df)
print('Mode:')
print(mode_df.head(2).to_string())
'''numerical_data[['first_ings_score', 'first_ings_wkts', 'second_ings_score',
       'second_ings_wkts', 'margin', 'highscore']].agg('mode') #match id is removed since the match id is unique'''
var_df=numerical_data.agg('var')
std_df=numerical_data.agg('std')
print('Variance:')
print(var_df)
print('standard deviation:')
print(std_df)

"""4.a"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
data=pd.read_csv('/content/Final Dataset - IPL.csv')
df=pd.DataFrame(data)
categorical_data=df.select_dtypes(include=object) # gives all the categorical data
numerical_data=df.select_dtypes(exclude=object) # gives all the numerical data
sns.pairplot(numerical_data) # gives all the relation between numeric data
plt.figure(figsize=(10,5))
sns.histplot(df['match_winner'],bins=15,color='purple')
plt.show()
plt.figure(figsize=(10,5))
r=df.groupby('match_winner')['match_id'].agg('count')
r=r.reset_index(name='count')
sns.barplot(data=r,x='match_winner',y='count')

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
data=pd.read_csv('/content/Final Dataset - IPL.csv')
df=pd.DataFrame(data)
categorical_data=df.select_dtypes(include=object) # gives all the categorical data
numerical_data=df.select_dtypes(exclude=object) # gives all the numerical data
corr=numerical_data.agg('corr')
sns.heatmap(corr)

"""6.by using boxplot ar any other methos by finding threshhold we can remove the outliners"""

threshhold=20
df=df[df['highscore']>20]
plt.boxplot(df['match_winner'],df['highscore'],hue='toss_decision')

"""7."""



"""8."""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
data=pd.read_csv('/content/Final Dataset - IPL.csv')
df=pd.DataFrame(data)
r=df.groupby(['player_of_the_match']).size()
r=r.reset_index(name='count')
r=r.sort_values(by='count',ascending=False)
print(r.head(1))

"""9"""

